language: node_js
node_js:
- 12

################
before_install:
- node --version
- npm --version
- npm install -g jest
- npm install
- mkdir tests/fonts
- wget -P tests/fonts https://github.com/google/fonts/raw/master/ofl/sourcesanspro/SourceSansPro-Regular.ttf
- npm install -g coveralls

################
script:
- npm run testrel