version: 2.1

workflows:
  test_mkdistmaps:
    jobs:
      - test

jobs:
  test:
    docker:
      - image: cimg/node:14.20.1
    steps:
      - checkout
      - run: node -v; npm -v
      - run: npm install jest
      - run: mkdir tests/output
      - run: npm install coveralls
      - run: npm run test
      - run: node node_modules/coveralls/bin/coveralls.js < coverage/lcov.info # .coveralls.yml must contain circleci
     #- sonarcloud/scan