version: 2.1
orbs:
  node: circleci/node@4.1.0
workflows:
  test_my_app:
    jobs:
      - test
jobs:
  test:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          cache-path: ~/project/node_modules
          override-ci-command: npm install
      - run: npm install jest
      - run: mkdir tests/fonts
      - run: wget -P tests/fonts https://github.com/google/fonts/raw/master/ofl/sourcesanspro/SourceSansPro-Regular.ttf
      - run: mkdir tests/output
      - run: npm install coveralls
      - run: npm run test
      - run: node node_modules/coveralls/bin/coveralls.js < coverage/lcov.info