version: 2.1
orbs:
  node: circleci/node@4.1.0
workflows:
  node-tests:
    jobs:
#      - npm install -g jest
#      - mkdir tests/fonts
#      - node/test
       - test-mkdistmaps

jobs:
  test-mkdistmaps:
    steps:
      - checkout
      - run:
          name: install-npm
          command: npm install
      - run:
          name: install-jest
          command: npm install jest
      - run:
          name: make-tests-fonts-directory
          command: mkdir tests/fonts
      - run:
          name: get-font-for-test
          command: wget -P tests/fonts https://github.com/google/fonts/raw/master/ofl/sourcesanspro/SourceSansPro-Regular.ttf
      - run:
          name: run-test
          command: npm run test
